name: Java Maven Spotless Apply and Commit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  spotless_apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Cho phép commit lại thay đổi vào nhánh
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Run Spotless Apply
        run: mvn spotless:apply
      - name: Commit and Push Changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Apply Spotless formatting"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
